In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
from pprint import pprint
import numpy as np
import requests
import time
import json
from scipy.stats import linregress
#from config import api_key

In [2]:
# Define an empty list to fetch data
fred_data = []

# Create Fred API

# Start date
earliest_realtime_start = 1980-1-1

# End date
latest_realtime_end = 1999-12-31

# Max amount of results
max_request_results = 1000

nan_char = '.'
# main URL used
root_url = "https://api.stlouisfed.org/fred"

# Create URL with endpoints: API 8d4aa278dda16f4a68ce9443e8feda2a
fred_url = "https://api.stlouisfed.org/fred/series/observations?series_id=GDP&api_key=8d4aa278dda16f4a68ce9443e8feda2a&file_type=json"

# Request data
fred_data = requests.get(fred_url)
fred_data = fred_data.json()
fred_data

{'realtime_start': '2023-05-29',
 'realtime_end': '2023-05-29',
 'observation_start': '1600-01-01',
 'observation_end': '9999-12-31',
 'units': 'lin',
 'output_type': 1,
 'file_type': 'json',
 'order_by': 'observation_date',
 'sort_order': 'asc',
 'count': 309,
 'offset': 0,
 'limit': 100000,
 'observations': [{'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1946-01-01',
   'value': '.'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1946-04-01',
   'value': '.'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1946-07-01',
   'value': '.'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1946-10-01',
   'value': '.'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1947-01-01',
   'value': '243.164'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1947-04-01',
   'value': '245.968'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1947-07-01',
   'value': '249.585'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1947-10-01',
   'value': '259.745'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1948-01-01',
   'value': '265.742'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1948-04-01',
   'value': '272.567'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1948-07-01',
   'value': '279.196'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1948-10-01',
   'value': '280.366'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1949-01-01',
   'value': '275.034'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1949-04-01',
   'value': '271.351'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1949-07-01',
   'value': '272.889'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1949-10-01',
   'value': '270.627'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1950-01-01',
   'value': '280.828'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1950-04-01',
   'value': '290.383'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1950-07-01',
   'value': '308.153'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1950-10-01',
   'value': '319.945'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1951-01-01',
   'value': '336.0'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1951-04-01',
   'value': '344.09'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1951-07-01',
   'value': '351.385'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1951-10-01',
   'value': '356.178'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1952-01-01',
   'value': '359.82'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1952-04-01',
   'value': '361.03'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1952-07-01',
   'value': '367.701'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1952-10-01',
   'value': '380.812'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1953-01-01',
   'value': '387.98'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1953-04-01',
   'value': '391.749'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1953-07-01',
   'value': '391.171'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1953-10-01',
   'value': '385.97'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1954-01-01',
   'value': '385.345'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1954-04-01',
   'value': '386.121'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1954-07-01',
   'value': '390.996'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1954-10-01',
   'value': '399.734'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1955-01-01',
   'value': '413.073'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1955-04-01',
   'value': '421.532'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1955-07-01',
   'value': '430.221'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1955-10-01',
   'value': '437.092'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1956-01-01',
   'value': '439.746'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1956-04-01',
   'value': '446.01'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1956-07-01',
   'value': '451.191'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1956-10-01',
   'value': '460.463'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1957-01-01',
   'value': '469.779'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1957-04-01',
   'value': '472.025'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1957-07-01',
   'value': '479.49'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1957-10-01',
   'value': '474.864'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1958-01-01',
   'value': '467.54'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1958-04-01',
   'value': '471.978'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1958-07-01',
   'value': '485.841'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1958-10-01',
   'value': '499.555'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1959-01-01',
   'value': '510.33'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1959-04-01',
   'value': '522.653'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1959-07-01',
   'value': '525.034'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1959-10-01',
   'value': '528.6'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1960-01-01',
   'value': '542.648'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1960-04-01',
   'value': '541.08'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1960-07-01',
   'value': '545.604'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1960-10-01',
   'value': '540.197'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1961-01-01',
   'value': '545.018'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1961-04-01',
   'value': '555.545'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1961-07-01',
   'value': '567.664'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1961-10-01',
   'value': '580.612'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1962-01-01',
   'value': '594.013'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1962-04-01',
   'value': '600.366'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1962-07-01',
   'value': '609.027'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1962-10-01',
   'value': '612.28'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1963-01-01',
   'value': '621.672'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1963-04-01',
   'value': '629.752'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1963-07-01',
   'value': '644.444'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1963-10-01',
   'value': '653.938'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1964-01-01',
   'value': '669.822'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1964-04-01',
   'value': '678.674'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1964-07-01',
   'value': '692.031'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1964-10-01',
   'value': '697.319'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1965-01-01',
   'value': '717.79'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1965-04-01',
   'value': '730.191'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1965-07-01',
   'value': '749.323'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1965-10-01',
   'value': '771.857'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1966-01-01',
   'value': '795.734'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1966-04-01',
   'value': '804.981'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1966-07-01',
   'value': '819.638'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1966-10-01',
   'value': '833.302'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1967-01-01',
   'value': '844.17'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1967-04-01',
   'value': '848.983'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1967-07-01',
   'value': '865.233'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1967-10-01',
   'value': '881.439'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1968-01-01',
   'value': '909.387'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1968-04-01',
   'value': '934.344'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1968-07-01',
   'value': '950.825'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1968-10-01',
   'value': '968.03'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1969-01-01',
   'value': '993.337'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1969-04-01',
   'value': '1009.02'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1969-07-01',
   'value': '1029.956'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1969-10-01',
   'value': '1038.147'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1970-01-01',
   'value': '1051.2'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1970-04-01',
   'value': '1067.375'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1970-07-01',
   'value': '1086.059'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1970-10-01',
   'value': '1088.608'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1971-01-01',
   'value': '1135.156'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1971-04-01',
   'value': '1156.271'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1971-07-01',
   'value': '1177.675'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1971-10-01',
   'value': '1190.297'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1972-01-01',
   'value': '1230.609'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1972-04-01',
   'value': '1266.369'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1972-07-01',
   'value': '1290.566'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1972-10-01',
   'value': '1328.904'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1973-01-01',
   'value': '1377.49'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1973-04-01',
   'value': '1413.887'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1973-07-01',
   'value': '1433.838'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1973-10-01',
   'value': '1476.289'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1974-01-01',
   'value': '1491.209'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1974-04-01',
   'value': '1530.056'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1974-07-01',
   'value': '1560.026'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1974-10-01',
   'value': '1599.679'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1975-01-01',
   'value': '1616.116'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1975-04-01',
   'value': '1651.853'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1975-07-01',
   'value': '1709.82'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1975-10-01',
   'value': '1761.831'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1976-01-01',
   'value': '1820.487'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1976-04-01',
   'value': '1852.332'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1976-07-01',
   'value': '1886.558'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1976-10-01',
   'value': '1934.273'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1977-01-01',
   'value': '1988.648'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1977-04-01',
   'value': '2055.909'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1977-07-01',
   'value': '2118.473'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1977-10-01',
   'value': '2164.27'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1978-01-01',
   'value': '2202.76'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1978-04-01',
   'value': '2331.633'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1978-07-01',
   'value': '2395.053'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1978-10-01',
   'value': '2476.949'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1979-01-01',
   'value': '2526.61'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1979-04-01',
   'value': '2591.247'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1979-07-01',
   'value': '2667.565'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1979-10-01',
   'value': '2723.883'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1980-01-01',
   'value': '2789.842'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1980-04-01',
   'value': '2797.352'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1980-07-01',
   'value': '2856.483'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1980-10-01',
   'value': '2985.557'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1981-01-01',
   'value': '3124.206'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1981-04-01',
   'value': '3162.532'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1981-07-01',
   'value': '3260.609'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1981-10-01',
   'value': '3280.818'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1982-01-01',
   'value': '3274.302'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1982-04-01',
   'value': '3331.972'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1982-07-01',
   'value': '3366.322'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1982-10-01',
   'value': '3402.561'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1983-01-01',
   'value': '3473.413'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1983-04-01',
   'value': '3578.848'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1983-07-01',
   'value': '3689.179'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1983-10-01',
   'value': '3794.706'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1984-01-01',
   'value': '3908.054'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1984-04-01',
   'value': '4009.601'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1984-07-01',
   'value': '4084.25'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1984-10-01',
   'value': '4148.551'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1985-01-01',
   'value': '4230.168'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1985-04-01',
   'value': '4294.887'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1985-07-01',
   'value': '4386.773'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1985-10-01',
   'value': '4444.094'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1986-01-01',
   'value': '4507.894'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1986-04-01',
   'value': '4545.34'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1986-07-01',
   'value': '4607.669'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1986-10-01',
   'value': '4657.627'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1987-01-01',
   'value': '4722.156'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1987-04-01',
   'value': '4806.16'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1987-07-01',
   'value': '4884.555'},
  {'realtime_start': '2023-05-29',
   'realtime_end': '2023-05-29',
   'date': '1987-10-01',
   'value': '5007.994'},

In [3]:
# Convert Datasets to Dataframe
fred_df = pd.DataFrame(fred_data["observations"])
fred_df.tail()

    realtime_start realtime_end        date      value
304     2023-05-29   2023-05-29  2022-01-01   24740.48
305     2023-05-29   2023-05-29  2022-04-01  25248.476
306     2023-05-29   2023-05-29  2022-07-01  25723.941
307     2023-05-29   2023-05-29  2022-10-01  26137.992
308     2023-05-29   2023-05-29  2023-01-01  26486.287

In [4]:
# Create an empty dataframe to hold all data
clean_fred_df = pd.DataFrame(columns= ["Realtime_Start",
                            "Realtime_end",
                            "Date",
                            "Value"])
clean_fred_df

Empty DataFrame
Columns: [Realtime_Start, Realtime_end, Date, Value]
Index: []

In [5]:
# Clean dataframe